Add OpenStack/AWS support

diff --git a/openio-sds-swift/Vagrantfile b/openio-sds-swift/Vagrantfile
--- a/openio-sds-swift/Vagrantfile
+++ b/openio-sds-swift/Vagrantfile
@@ -3,46 +3,88 @@
 
 Vagrant.configure(2) do |config|
 
+  # Gloval env variables
+  PROFILE = 'swift'
+  VAGRANT_PROVIDER = ENV['VAGRANT_PROVIDER'] || 'virtualbox'
+  abort "Unsupported provider #{VAGRANT_PROVIDER}. Aborting." unless ['virtualbox','openstack','aws'].include?(VAGRANT_PROVIDER)
+  openio_mirror = ENV['OIO_MIRROR'] || 'http://mirror.openio.io/pub/repo/openio/sds'
+  add_repo = ENV['ADD_REPO'] || nil
   openstack_repo = 'https://repos.fedorapeople.org/repos/openstack/openstack-juno/rdo-release-juno-1.noarch.rpm'
   openio_mirror = ENV['OIO_MIRROR'] || 'http://mirror.openio.io/pub/repo/openio/sds'
 
-  # Box configuration
-  config.vm.box = "openio/sds"
-  config.vm.network "private_network", :type => 'dhcp', :adapter => 2
-  config.vm.network "public_network" , :type => 'dhcp', :adapter => 3
+  # Global box configuration
+  config.vm.box  = "openio/sds-{#PROFILE}"
+  config.ssh.pty = true
   config.vm.synced_folder '.', '/var/lib/oio/vagrant', disabled: true
 
-  # use "openio" as default user instead of "vagrant"
-  config.ssh.username = "openio"
-  config.ssh.password = ""
 
-  # VirtualBox Specific
+  # VirtualBox
+  if VAGRANT_PROVIDER == 'virtualbox'
+    puts 'Using the virtualbox provider ...'
+    config.vm.network "private_network", :type => 'dhcp', :adapter => 2
+    config.vm.network "public_network" , :type => 'dhcp', :adapter => 3
+    # use "openio" as default user instead of "vagrant"
+    config.ssh.username = "openio"
+  end
   config.vm.provider :virtualbox do |virtualbox|
     virtualbox.gui = true
-    virtualbox.name = "OpenIO-SDS-Swift"
+    virtualbox.name = "OpenIO-SDS-#{PROFILE}"
     virtualbox.cpus = "1"
     virtualbox.memory = "1024"
   end
 
-  # VMware Fusion/Workstation Specfic
-  config.vm.provider "vmware_desktop" do |vmware|
-    vmware.gui = true
-    vmware.vmx['displayname'] = "OpenIO-SDS"
-    vmware.vmx["numvcpus"] = "1"
-    vmware.vmx["memsize"] = "1024"
+  # OpenStack
+  config.vm.provider :openstack do |os,override|
+    os.server_name                = "OpenIO-SDS-#{PROFILE}"
+    os.openstack_auth_url         = ENV['OS_OPENSTACK_AUTH_URL']
+    os.username                   = ENV['OS_USERNAME']
+    os.password                   = ENV['OS_PASSWORD']
+    os.tenant_name                = ENV['OS_TENANT_NAME']
+    os.flavor                     = ENV['OS_FLAVOR'] || 'm1.small'
+    os.image                      = ENV['OS_IMAGE'] || 'CentOS-7-x86_64-GenericCloud'
+    os.floating_ip_pool           = ENV['OS_FLOATING_IP_POOL'] || []
+    os.networks                   = ENV['OS_NETWORKS'] || []
+    os.keypair_name               = ENV['OS_KEYPAIR']
+    os.sync_method                = ENV['OS_SYNC_METHOD'] || 'none'
+    os.server_name                = ENV['OS_SERVER_NAME'] || "OpenIO-SDS-#{PROFILE}"
+    override.ssh.private_key_path = ENV['OS_SSH_PRIVATE_KEY_PATH'] || '~/.ssh/id_rsa'
+    override.ssh.username         = ENV['OS_SSH_USERNAME'] || 'centos'
+    override.ssh.insert_key       = ENV['OS_SSH_INSERT_KEY'] || true
   end
+
+  # AWS
+  config.vm.provider :aws do |aws, override|
+    aws.tags["Name"]              = "OpenIO-SDS-#{PROFILE}"
+    aws.access_key_id             = ENV['AWS_ACCESS_KEY_ID']
+    aws.secret_access_key         = ENV['AWS_SECRET_ACCESS_KEY']
+    aws.keypair_name              = ENV['AWS_KEYPAIR']
+    aws.region                    = ENV['AWS_REGION'] || 'eu-central-1'
+    aws.ami                       = ENV['AWS_AMI'] || 'ami-e68f82fb'
+    aws.availability_zone         = ENV['AWS_AVAILABILITY_ZONE'] || 'eu-central-1a'
+    aws.instance_type             = ENV['AWS_INSTANCE_TYPE'] || 't2.micro'
+    aws.security_groups           = ENV['AWS_SECURITY_GROUPS']
+    aws.associate_public_ip       = ENV['AWS_ASSOCIATE_PUBLIC_IP'] || true
+    aws.elastic_ip                = ENV['AWS_ELASTIC_IP'] || false
+    aws.subnet_id                 = ENV['AWS_SUBNET_ID']
+    override.vm.box               = ENV['AWS_VM_BOX'] || 'dummy'
+    override.vm.box_url           = ENV['AWS_VM_BOX_URL'] || 'https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box'
+    override.ssh.username         = ENV['AWS_SSH_USERNAME'] || 'centos'
+    override.ssh.private_key_path = ENV['AWS_SSH_PRIVATE_KEY_PATH'] || '~/.ssh/id_rsa'
+    override.ssh.insert_key       = ENV['AWS_SSH_INSERT_KEY'] || true
+  end
+
 
   # Provisionning OpenIO SDS
   config.vm.provision "shell", inline: <<-SHELL
     /usr/bin/yum -y install wget
     release=$(/bin/wget #{openio_mirror}/latest -q -O -)
     /usr/bin/yum -y install http://mirror.openio.io/pub/repo/openio/sds/\$release/el/openio-sds-release-\$release-1.el.noarch.rpm #{openstack_repo}
-    /usr/bin/yum -y install puppet-openio-sds-profile-swift memcached redis python-swiftclient
+    /usr/bin/yum -y install puppet-openio-sds-profile-#{PROFILE} memcached redis python-swiftclient
     /usr/bin/puppet module install stackforge-keystone
     /usr/bin/systemctl enable memcached.service redis.service
     /usr/bin/systemctl start memcached.service
     /usr/bin/systemctl start redis.service
-    /usr/share/puppet/modules/openiosds/profiles/install.sh swift
+    /usr/share/puppet/modules/openiosds/profiles/install.sh #{PROFILE}
     echo "export OS_TENANT_NAME=demo
 export OS_USERNAME=demo
 export OS_PASSWORD=DEMO_PASS
